
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: twitter-inbound
  labels:
    strimzi.io/cluster: subzero
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824