apiVersion: v1
kind: List
metadata:
  labels:
    application: quarkus-techlab
items:

  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        application: quarkus-techlab
      name: twitter-data-transformer

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        application: quarkus-techlab
      name: twitter-data-transformer
    spec:
      replicas: 1
      selector:
        deploymentConfig: twitter-data-transformer
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            application: quarkus-techlab
            deploymentConfig: twitter-data-transformer
        spec:
          containers:
            - image: twitter-data-transformer
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 5
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 3
                periodSeconds: 20
                successThreshhold: 1
                timeoutSeconds: 15
              readinessProbe:
                failureThreshold: 5
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 3
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 15
              name: twitter-data-transformer
              port:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              resources:
                limits:
                  cpu: 1
                  memory: 500Mi
                requests:
                  cpu: 50m
                  memory: 100Mi
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - twitter-data-transformer
            from:
              kind: ImageStreamTag
              name: twitter-data-transformer:latest
          type: ImageChange
        - type: ConfigChange

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        application: quarkus-techlab
      name: twitter-data-transformer
    spec:
      ports:
        - name: twitter-data-transformer-http
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentConfig: twitter-data-transformer
      sessionAffinity: None
      type: ClusterIP

  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        application: quarkus-techlab
      name: twitter-data-transformer
    spec:
      port:
        targetPort: twitter-data-transformer-http
      tls:
        termination: edge
      to:
        kind: Service
        name: twitter-data-transformer
        weight: 100
      wildcardPolicy: None
