apiVersion: v1
kind: Template
metadata:
  name: pipeline-resources-template
  annotations:
    description: 'Template to create project specific Pipeline resources'
objects:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: data-consumer-repo
    spec:
      type: git
      params:
        - name: url
          value: https://github.com/g1raffi/devtre-kafka.git
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: data-consumer-image
    spec:
      type: image
      params:
        - name: url
          value: image-registry.openshift-image-registry.svc:5000/devtre-kafka/data-consumer:latest